on:
  slack:
    force: true
    token: ${{ secrets.SLACK_TOKEN }}
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          slack_outputs: ${{ toJson(on.slack.outputs) }}
        run: |
          echo telegram: $slack_outputs
