on:
  twitter:
    continue-on-error: true
    event: new_my_tweets
    auth:
      consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      access_token_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
    params:
      screen_name: theowenyoung
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        if: on.twitter.outcome==='failure'
        env:
          text: ${{ on.twitter.outputs.text }}
          outcome: ${{ on.twitter.outcome }}
        run: |
          echo text: $outcome
