name: "Actionsflow Action"
author: Actionsflow
description: "Run Actionsflow in Github"
inputs:
  using:
    descript: "actionsflow runner using, the default value is auto, auto to detect is using local npm to build"
    required: false
  args:
    description: "actionsflow args, the default value is build"
    required: false
outputs:
  success:
    description: "If the build status is success, value can be 'true', or 'false', if build failed, the action outcome will be set failed"
runs:
  using: "node12"
  main: "packages/actionsflow-action/dist/main/index.js"
  pre: "packages/actionsflow-action/dist/pre/index.js"
branding:
  icon: "send"
  color: "blue"
